<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-BTBHOBIS" ignored="4" name="Test(failed)" tests="3" failures="1" timestamp="2021-12-02T13:37:31 IST" time="0.108" errors="0">
  <testcase name="TC3" time="0.014" classname="com.atipune.testngframe.basics.Failedtestcase"/>
  <testcase name="TC5" time="0.002" classname="com.atipune.testngframe.basics.Failedtestcase"/>
  <testcase name="TC1" time="0.005" classname="com.atipune.testngframe.basics.Failedtestcase">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.atipune.testngframe.basics.Failedtestcase.TC1(Failedtestcase.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC1 -->
  <testcase name="TC2" time="0.0" classname="com.atipune.testngframe.basics.Failedtestcase">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase name="TC7" time="0.0" classname="com.atipune.testngframe.basics.Failedtestcase">
    <ignored/>
  </testcase> <!-- TC7 -->
  <testcase name="TC4" time="0.0" classname="com.atipune.testngframe.basics.Failedtestcase">
    <ignored/>
  </testcase> <!-- TC4 -->
  <testcase name="TC6" time="0.0" classname="com.atipune.testngframe.basics.Failedtestcase">
    <ignored/>
  </testcase> <!-- TC6 -->
</testsuite> <!-- Test(failed) -->
